# WAP to read a user personal information like name, emailid, mobile, city and address
name = input("Enter your name : ")
emailId = input("Enter your email id : ")
mobile = input("Enter your mobile : ")
city = input("Enter your city : ")
address = input("Enter your address : ")
print("Your Details")
print("Name : ",name)
print("Email Id : ",emailId)
print("Mobile : ",mobile)
print("City : ",city)
print("Address : ",address)
